// Textos de interface e de páginas (PT/EN). Nomes próprios não são traduzidos.
// Itens com `pending: true` são pendências de conteúdo do sitemap — aparecem
// sinalizados no site até serem confirmados.

export const copy = {
  pt: {
    lang: 'pt-BR',
    ui: {
      skip: 'Pular para o conteúdo',
      nav: { projects: 'Projetos', about: 'Sobre', contact: 'Contato' },
      navLabel: 'Navegação principal',
      langLabel: 'Idioma',
      menuOpen: 'Abrir menu',
      menuClose: 'Fechar menu',
      home: 'Início',
      viewProject: 'Ver projeto',
      unavailable: 'Indisponível',
      linkPending: 'Link a confirmar',
      placeholder: 'Imagem provisória',
      conceptBadge: 'Projeto conceito — persona fictícia',
      pending: 'Pendente',
      back: 'Voltar',
      projectNav: 'Navegar entre projetos',
      prevProject: 'Projeto anterior',
      nextProject: 'Próximo projeto',
    },
    meta: {
      home: { title: 'João Riedo — Product Designer', description: 'Portfólio de João Riedo, Product Designer. Design de produtos digitais, da estrutura à experiência.' },
      projects: { title: 'Projetos — João Riedo', description: 'Projetos de João Riedo: Design System Multi-tenant, Instituto MAIS, Dr. Carlos Mattos e Marina Alves.' },
      about: { title: 'Sobre — João Riedo', description: 'Trajetória, forma de trabalho, formação e diferenciais de João Riedo, Product Designer.' },
      contact: { title: 'Contato — João Riedo', description: 'Vamos conversar sobre o seu projeto? Envie uma mensagem para João Riedo pelo WhatsApp.' },
      notFound: { title: 'Página não encontrada — João Riedo', description: 'A página procurada não existe.' },
    },
    home: {
      name: 'João Riedo',
      role: 'Product Designer',
      headline: 'Design de produtos digitais, da estrutura à experiência.',
      bio: 'Product Designer na Multibet, com experiência anterior na Ana Gaming.',
      cta: 'Explorar projetos',
      boxLabel: 'Composição tipográfica com as letras da palavra PORTFÓLIO',
      selectedTitle: 'Projetos selecionados',
      allProjects: 'Ver todos os projetos',
      scrollHint: 'Role para avançar',
    },
    projects: {
      title: 'Projetos',
      intro: 'Design system, sites e landing pages, com problema, papel e decisões em volta de cada um.',
    },
    project: {
      breadcrumb: 'Projetos',
      facts: { role: 'Papel', duration: 'Duração', platform: 'Plataforma', team: 'Equipe' },
      live: 'Abrir site ao vivo',
      liveUnavailable: 'Site ainda não publicado neste domínio',
      mediaKit: 'Baixar mídia kit (PDF)',
      mediaKitUnavailable: 'Mídia kit (PDF) em breve',
      demoTitle: 'Demonstração',
      desktop: 'Desktop',
      mobile: 'Mobile',
      fullscreen: 'Tela cheia',
      exitFullscreen: 'Sair da tela cheia',
      demoPlaceholder: 'Demonstração provisória',
      demoPlaceholderText: 'O site navegável será incorporado aqui. Enquanto isso, esta é uma prévia local.',
      demoLoading: 'Carregando o site…',
      demoUnavailable: 'Não foi possível exibir o site aqui.',
      demoFallback: 'Veja a prévia abaixo ou abra o site em uma nova aba.',
      contextTitle: 'Contexto',
      decisionsTitle: 'Decisões de design',
      numbersTitle: 'O projeto em números',
      numbersNote: 'Números que descrevem o escopo do projeto, não resultados de negócio.',
      next: 'Próximo projeto',
    },
    about: {
      title: 'Criando sistemas que ajudam equipes e produtos a escalar',
      intro: 'Sou Product Designer na Multibet, onde trabalho em um portfólio de produtos para diferentes mercados. Antes, fui UX Designer na Ana Gaming.',
      focusTitle: 'Design Systems, Design Ops e IA aplicada',
      // rascunho editorial — sem fatos novos
      focusText: 'Meu trabalho vai da estrutura à interface: sistemas de design que mantêm produtos consistentes, processos que tornam o time mais rápido e ferramentas de IA incorporadas ao fluxo de trabalho.',
      philosophyTitle: 'Como eu trabalho',
      philosophy: [
        'Design vai além da estética. Cada decisão visual precisa responder a um problema de quem usa o produto e de quem o constrói.',
        'Design Ops com IA: uso ferramentas de IA para acelerar o que é repetitivo (documentação, variações, revisões) e deixar mais tempo para as decisões que pedem julgamento.',
        'O handoff faz parte do design. Especificações claras, componentes documentados e conversa próxima com desenvolvimento evitam que a intenção se perca na implementação.',
      ],
      differentialsTitle: 'Diferenciais',
      differentials: [
        { title: 'Design Systems & Ops', text: 'Tokens, componentes e processos que sustentam produtos em escala.' },
        { title: 'Produto de ponta a ponta', text: 'Da pesquisa e da arquitetura da informação à interface e ao front-end.' },
        { title: 'IA no workflow', text: 'Ferramentas de IA aplicadas à rotina de design e documentação.' },
        { title: 'Mentalidade global', text: 'Experiência com produtos para mercados da América Latina e da Ásia.' },
      ],
      timelineTitle: 'Trajetória',
      timeline: [
        { org: 'Multibet', role: 'Product Designer', period: 'fev/2026–atual' },
        { org: 'Ana Gaming', role: 'UX Designer', period: 'abr–dez/2025' },
        { org: 'Alterra', role: 'Intercâmbio com foco no inglês', period: 'dez/2023–mar/2024' },
        { org: 'Instituto ESPE', role: 'Supervisor de Design', period: 'set/2020–jul/2023' },
      ],
      educationTitle: 'Formação e skills',
      education: [
        { org: 'UniFil', course: 'Bacharelado em Design Gráfico', period: '2020–2022' },
        { org: 'IFPR', course: 'Técnico Integrado em Informática', period: '2015–2018' },
      ],
      skillsTitle: 'Top skills',
      skills: ['Claude Cowork', 'Automação de Workflow', 'Design Tokens', 'Design Ops', 'iGaming & Sportsbook', 'Pesquisa de Mercado', 'Prototipagem de Alta Fidelidade'],
      certificationsTitle: 'Certificações',
      certifications: [
        { name: 'Google UX Design Professional Certificate', issuer: 'Google (Coursera)', url: 'https://www.coursera.org/account/accomplishments/specialization/Y2WKA6Q7A19U' },
        { name: 'Claude for Designers', issuer: 'Tera', url: 'https://credentials.somostera.com/d2a2aaf94c6cd04c9afdf55dcdadbebb' },
      ],
      verify: 'Ver certificado',
      contactTitle: 'Contato direto',
      contactText: 'Para propostas e conversas sobre projetos, a forma mais rápida é a página de contato.',
      contactCta: 'Ir para contato',
      cvTitle: 'Currículo',
      cvPt: 'Baixar CV em português',
      cvEn: 'Baixar CV em inglês',
      cvUnavailable: 'Arquivo ainda não disponível',
      photoAlt: 'Foto de João Riedo',
    },
    contact: {
      title: 'Vamos conversar sobre o seu projeto?',
      text: 'Escreva seu nome e sua mensagem. Ao enviar, o WhatsApp abre com o texto pronto para você revisar e enviar.',
      otherChannels: 'Outros canais',
    },
    form: {
      title: 'Vamos conversar sobre o seu projeto?',
      text: 'A mensagem abre no WhatsApp com o texto pronto. Nada é enviado automaticamente.',
      name: 'Nome',
      message: 'Mensagem',
      submit: 'Enviar no WhatsApp',
      nameError: 'Informe seu nome.',
      messageError: 'Escreva uma mensagem.',
      greeting: (name) => `Olá, João! Aqui é ${name}.`,
      demoNotice: 'Modo demonstração: o número de WhatsApp ainda não foi configurado, então nenhuma conversa será aberta.',
      demoPreview: 'Esta seria a mensagem enviada:',
      opened: 'O WhatsApp foi aberto em uma nova aba com a sua mensagem.',
    },
    footer: {
      title: 'Tem um projeto em mente?',
      text: 'Conte o que você precisa. Respondo pelo WhatsApp.',
      cta: 'Entrar em contato',
      rights: 'Todos os direitos reservados.',
      linksLabel: 'Links',
    },
    notFound: {
      title: 'Esta página não existe',
      text: 'O endereço pode ter mudado. Os projetos continuam aqui:',
      cta: 'Ver projetos',
    },
  },

  en: {
    lang: 'en',
    ui: {
      skip: 'Skip to content',
      nav: { projects: 'Projects', about: 'About', contact: 'Contact' },
      navLabel: 'Main navigation',
      langLabel: 'Language',
      menuOpen: 'Open menu',
      menuClose: 'Close menu',
      home: 'Home',
      viewProject: 'View project',
      unavailable: 'Unavailable',
      linkPending: 'Link to be confirmed',
      placeholder: 'Placeholder image',
      conceptBadge: 'Concept project — fictional persona',
      pending: 'Pending',
      back: 'Back',
      projectNav: 'Browse projects',
      prevProject: 'Previous project',
      nextProject: 'Next project',
    },
    meta: {
      home: { title: 'João Riedo — Product Designer', description: 'Portfolio of João Riedo, Product Designer. Designing digital products, from structure to experience.' },
      projects: { title: 'Projects — João Riedo', description: 'Projects by João Riedo: Multi-tenant Design System, Instituto MAIS, Dr. Carlos Mattos and Marina Alves.' },
      about: { title: 'About — João Riedo', description: 'Background, way of working, education and strengths of João Riedo, Product Designer.' },
      contact: { title: 'Contact — João Riedo', description: 'Shall we talk about your project? Send João Riedo a message on WhatsApp.' },
      notFound: { title: 'Page not found — João Riedo', description: 'The page you are looking for does not exist.' },
    },
    home: {
      name: 'João Riedo',
      role: 'Product Designer',
      headline: 'Designing digital products, from structure to experience.',
      bio: 'Product Designer at Multibet, previously at Ana Gaming.',
      cta: 'Explore projects',
      boxLabel: 'Typographic composition with the letters of the word PORTFÓLIO',
      selectedTitle: 'Selected projects',
      allProjects: 'See all projects',
      scrollHint: 'Scroll to advance',
    },
    projects: {
      title: 'Projects',
      intro: 'A design system, websites and landing pages, each with the problem, role and decisions around it.',
    },
    project: {
      breadcrumb: 'Projects',
      facts: { role: 'Role', duration: 'Duration', platform: 'Platform', team: 'Team' },
      live: 'Open live site',
      liveUnavailable: 'Site not yet published on this domain',
      mediaKit: 'Download media kit (PDF)',
      mediaKitUnavailable: 'Media kit (PDF) coming soon',
      demoTitle: 'Demo',
      desktop: 'Desktop',
      mobile: 'Mobile',
      fullscreen: 'Full screen',
      exitFullscreen: 'Exit full screen',
      demoPlaceholder: 'Placeholder demo',
      demoPlaceholderText: 'The navigable site will be embedded here. Meanwhile, this is a local preview.',
      demoLoading: 'Loading the site…',
      demoUnavailable: 'The site can’t be displayed here.',
      demoFallback: 'See the preview below or open the site in a new tab.',
      contextTitle: 'Context',
      decisionsTitle: 'Design decisions',
      numbersTitle: 'The project in numbers',
      numbersNote: 'Numbers describing the project’s scope, not business results.',
      next: 'Next project',
    },
    about: {
      title: 'Building systems that help teams and products scale',
      intro: 'I’m a Product Designer at Multibet, working on a portfolio of products for different markets. Before that, I was a UX Designer at Ana Gaming.',
      focusTitle: 'Design Systems, Design Ops and applied AI',
      focusText: 'My work goes from structure to interface: design systems that keep products consistent, processes that make teams faster and AI tools built into the workflow.',
      philosophyTitle: 'How I work',
      philosophy: [
        'Design goes beyond aesthetics. Every visual decision has to answer a problem for the people who use the product and the people who build it.',
        'Design Ops with AI: I use AI tools to speed up the repetitive parts (documentation, variations, reviews), leaving more time for decisions that need judgment.',
        'Handoff is part of design. Clear specs, documented components and close conversation with engineering keep intent from getting lost in implementation.',
      ],
      differentialsTitle: 'Strengths',
      differentials: [
        { title: 'Design Systems & Ops', text: 'Tokens, components and processes that support products at scale.' },
        { title: 'End-to-end product', text: 'From research and information architecture to interface and front-end.' },
        { title: 'AI in the workflow', text: 'AI tools applied to everyday design and documentation work.' },
        { title: 'Global mindset', text: 'Experience with products for Latin American and Asian markets.' },
      ],
      timelineTitle: 'Experience',
      timeline: [
        { org: 'Multibet', role: 'Product Designer', period: 'Feb 2026–present' },
        { org: 'Ana Gaming', role: 'UX Designer', period: 'Apr–Dec 2025' },
        { org: 'Alterra', role: 'Exchange program focused on English', period: 'Dec 2023–Mar 2024' },
        { org: 'Instituto ESPE', role: 'Design Supervisor', period: 'Sep 2020 — Jul 2023' },
      ],
      educationTitle: 'Education and skills',
      education: [
        { org: 'UniFil', course: 'Bachelor’s in Graphic Design', period: '2020–2022' },
        { org: 'IFPR', course: 'Integrated IT Technician', period: '2015–2018' },
      ],
      skillsTitle: 'Top skills',
      skills: ['Claude Cowork', 'Workflow Automation', 'Design Tokens', 'Design Ops', 'iGaming & Sportsbook', 'Market Research', 'High-Fidelity Prototyping'],
      certificationsTitle: 'Certifications',
      certifications: [
        { name: 'Google UX Design Professional Certificate', issuer: 'Google (Coursera)', url: 'https://www.coursera.org/account/accomplishments/specialization/Y2WKA6Q7A19U' },
        { name: 'Claude for Designers', issuer: 'Tera', url: 'https://credentials.somostera.com/d2a2aaf94c6cd04c9afdf55dcdadbebb' },
      ],
      verify: 'View certificate',
      contactTitle: 'Direct contact',
      contactText: 'For proposals and project conversations, the contact page is the fastest way.',
      contactCta: 'Go to contact',
      cvTitle: 'Résumé',
      cvPt: 'Download résumé in Portuguese',
      cvEn: 'Download résumé in English',
      cvUnavailable: 'File not available yet',
      photoAlt: 'Photo of João Riedo',
    },
    contact: {
      title: 'Shall we talk about your project?',
      text: 'Write your name and message. When you send it, WhatsApp opens with the text ready for you to review and send.',
      otherChannels: 'Other channels',
    },
    form: {
      title: 'Shall we talk about your project?',
      text: 'Your message opens in WhatsApp, ready to send. Nothing is sent automatically.',
      name: 'Name',
      message: 'Message',
      submit: 'Send on WhatsApp',
      nameError: 'Please enter your name.',
      messageError: 'Please write a message.',
      greeting: (name) => `Hi João! This is ${name}.`,
      demoNotice: 'Demo mode: the WhatsApp number hasn’t been set up yet, so no conversation will be opened.',
      demoPreview: 'This is the message that would be sent:',
      opened: 'WhatsApp opened in a new tab with your message.',
    },
    footer: {
      title: 'Have a project in mind?',
      text: 'Tell me what you need. I reply on WhatsApp.',
      cta: 'Get in touch',
      rights: 'All rights reserved.',
      linksLabel: 'Links',
    },
    notFound: {
      title: 'This page doesn’t exist',
      text: 'The address may have changed. The projects are still here:',
      cta: 'See projects',
    },
  },
};
