// Textos de interface e de páginas (PT/EN). Nomes próprios não são traduzidos.
// Itens com `pending: true` são pendências de conteúdo do sitemap — aparecem
// sinalizados no site até serem confirmados.

export const copy = {
  pt: {
    lang: 'pt-BR',
    ui: {
      skip: 'Pular para o conteúdo',
      nav: { projects: 'Projetos', about: 'Sobre', contact: 'Contato' },
      navLabel: 'Navegação principal',
      langLabel: 'Idioma',
      menuOpen: 'Abrir menu',
      menuClose: 'Fechar menu',
      home: 'Início',
      viewProject: 'Ver projeto',
      unavailable: 'Indisponível',
      linkPending: 'Link a confirmar',
      placeholder: 'Imagem provisória',
      conceptBadge: 'Projeto conceito — persona fictícia',
      pending: 'Pendente',
      back: 'Voltar',
      projectNav: 'Navegar entre projetos',
      prevProject: 'Projeto anterior',
      nextProject: 'Próximo projeto',
    },
    meta: {
      home: { title: 'João Riedo — Product Designer', description: 'Portfólio de João Riedo, Product Designer. Design de produtos digitais, da estrutura à experiência.' },
      projects: { title: 'Projetos — João Riedo', description: 'Projetos de João Riedo: Design System Multi-tenant, Instituto MAIS, Dr. Carlos Mattos e Marina Alves.' },
      about: { title: 'Sobre — João Riedo', description: 'Trajetória, competências, formação e certificações de João Riedo, Product Designer com foco em UX/UI e Design Systems.' },
      contact: { title: 'Contato — João Riedo', description: 'Me fale sobre seu projeto. Envie uma mensagem para João Riedo pelo WhatsApp.' },
      notFound: { title: 'Página não encontrada — João Riedo', description: 'A página procurada não existe.' },
    },
    home: {
      name: 'João Riedo',
      role: 'Product Designer',
      headline: 'Design de produtos digitais, da estrutura à experiência.',
      bio: 'Transformei ambiguidade em interfaces que realmente funcionam!',
      cta: 'Explorar projetos',
      skillsLabel: 'Competências',
      selectedTitle: 'Projetos selecionados',
      scrollHint: 'Role para avançar',
      testimonialsTitle: 'Quem já trabalhou comigo',
      testimonialsNav: 'Navegar entre depoimentos',
      prevTestimonial: 'Depoimento anterior',
      nextTestimonial: 'Próximo depoimento',
    },
    projects: {
      title: 'Projetos',
      intro: 'Design system, sites e landing pages que criei, com o desafio, a solução e o resultado de cada um.',
    },
    project: {
      breadcrumb: 'Projetos',
      facts: { role: 'Papel', duration: 'Duração', platform: 'Plataforma', team: 'Equipe' },
      live: 'Abrir site ao vivo',
      liveUnavailable: 'Site ainda não publicado neste domínio',
      mediaKit: 'Baixar mídia kit (PDF)',
      mediaKitUnavailable: 'Mídia kit (PDF) em breve',
      demoTitle: 'Demonstração',
      desktop: 'Desktop',
      mobile: 'Mobile',
      fullscreen: 'Tela cheia',
      exitFullscreen: 'Sair da tela cheia',
      demoPlaceholder: 'Demonstração provisória',
      demoPlaceholderText: 'O site navegável será incorporado aqui. Enquanto isso, esta é uma prévia local.',
      demoLoading: 'Carregando o site…',
      demoUnavailable: 'Não foi possível exibir o site aqui.',
      demoFallback: 'Veja a prévia abaixo ou abra o site em uma nova aba.',
      challengeTitle: 'Desafio',
      solutionTitle: 'Solução',
      resultTitle: 'Resultado',
      numbersNote: 'Os números abaixo descrevem o escopo do projeto, não resultados de negócio.',
      next: 'Próximo projeto',
    },
    about: {
      // Alinhado ao CV base (joao-riedo-cv-base-pt.docx), revisado em 01/10/2026.
      title: 'Criei sistemas que ajudaram equipes e produtos a escalar',
      intro: 'Construí minha trajetória em design gráfico, liderança de equipe e produtos digitais B2B/B2C. Atuei como Product Designer na Multibet e, antes, como UX Designer na Cassino.bet e na 7K.bet (Ana Gaming).',
      focusTitle: 'Design Systems, Design Ops e IA aplicada',
      focusText: 'Combinei análise de comportamento, arquitetura da informação e design de interfaces com documentação e colaboração próxima com Engenharia. Estruturei sistemas compartilhados entre marcas e conduzi redesigns com resultados de negócio.',
      philosophyTitle: 'Como eu trabalho',
      philosophy: [
        'Tratei design como mais do que estética: cada decisão visual que tomei respondeu a um problema de quem usa o produto e de quem o constrói.',
        'Design Ops com IA: usei Claude, ChatGPT, Figma Agent e workflows com Figma MCP e Notion MCP para acelerar ideação, prototipação, documentação e tarefas repetitivas, e deixar mais tempo para as decisões que pedem julgamento.',
        'Tratei o handoff como parte do design: entreguei especificações claras, componentes documentados e registros de decisões (DDRs) para que a intenção não se perdesse na implementação.',
      ],
      differentialsTitle: 'Diferenciais',
      differentials: [
        { title: 'Design Systems multi-tenant', text: 'Estruturei um Design System com 87 telas, mais de 200 componentes e 3 tenants em produção, com redução estimada de 80% no tempo de criação de telas.' },
        { title: 'Redesign com resultado', text: 'Liderei o redesign do sportsbook da Cassino.bet; um mês após a publicação, as apostas esportivas passaram de 3% para 10% do volume de apostas.' },
        { title: 'Produto de ponta a ponta', text: 'Conduzi projetos do discovery e da arquitetura da informação à interface, e implementei páginas web com HTML, CSS e JavaScript.' },
        { title: 'Liderança e processos', text: 'Liderei uma equipe de 4 pessoas, implementei Kanban e facilitei retrospectivas do time de Produto.' },
      ],
      timelineTitle: 'Trajetória',
      timeline: [
        { org: 'Multibet', role: 'Product Designer', period: 'fev–set/2026', note: 'Conduzi o design de produto em uma plataforma B2B multi-tenant e estruturei o Design System da operação white-label da Supernova, aplicado também a Play4tune e Multibet.' },
        { org: 'Cassino.bet e 7K.bet (Ana Gaming)', role: 'UX Designer', period: 'abr–dez/2025', note: 'Liderei o redesign do sportsbook da Cassino.bet, estruturei a arquitetura da informação das duas marcas e iniciei as bases de um Design System compartilhado.' },
        { org: 'Alterra Mountain Company', role: 'Work and Travel', period: 'dez/2023–mar/2024', note: 'Participei da temporada de inverno em Snowshoe, EUA, e aprimorei meu inglês no dia a dia profissional.' },
        { org: 'Instituto ESPE', role: 'Supervisor de Design', period: 'set/2020–jul/2023', note: 'Supervisionei a produção de design gráfico e digital e liderei uma equipe de 4 pessoas.' },
      ],
      educationTitle: 'Formação e skills',
      education: [
        { org: 'UniFil — Centro Universitário Filadélfia', course: 'Bacharelado em Design Gráfico', period: '2020–2022' },
        { org: 'IFPR, Londrina', course: 'Técnico Integrado em Informática', period: '2015–2018' },
      ],
      skillsTitle: 'Competências',
      skills: ['UI e Prototipação', 'Design Systems', 'UX e Pesquisa', 'IA Aplicada', 'Desenvolvimento Web', 'Metodologias e Processos', 'Gestão e Soft Skills'],
      languagesTitle: 'Idiomas',
      languages: 'Português nativo · Inglês avançado',
      certificationsTitle: 'Certificações',
      certifications: [
        { name: 'Google UX Design Professional Certificate', issuer: 'Google / Coursera · 2026', url: 'https://www.coursera.org/account/accomplishments/specialization/Y2WKA6Q7A19U' },
        { name: 'Claude for Designers', issuer: 'Tera · 2026', url: 'https://credentials.somostera.com/d2a2aaf94c6cd04c9afdf55dcdadbebb' },
        { name: 'CCUSA Work Experience', issuer: 'CCUSA · Temporada de inverno 2023/2024', url: null, noLink: true },
      ],
      verify: 'Ver certificado',
      contactTitle: 'Contato direto',
      contactText: 'Para propostas e conversas sobre projetos, a forma mais rápida é a página de contato.',
      contactCta: 'Ir para contato',
      cvTitle: 'Currículo',
      cvPt: 'Baixar CV em português',
      cvEn: 'Baixar CV em inglês',
      cvUnavailable: 'Arquivo ainda não disponível',
      photoAlt: 'Foto de João Riedo',
    },
    contact: {
      title: 'Me fale sobre seu projeto',
      text: 'Me conte sua ideia e vamos conversar sobre como posso ajudar.',
      otherChannels: 'Outros canais',
    },
    form: {
      title: 'Vamos conversar sobre o seu projeto?',
      text: 'A mensagem abre no WhatsApp com o texto pronto. Nada é enviado automaticamente.',
      name: 'Nome',
      message: 'Mensagem',
      submit: 'Enviar no WhatsApp',
      nameError: 'Informe seu nome.',
      messageError: 'Escreva uma mensagem.',
      greeting: (name) => `Olá, João! Aqui é ${name}.`,
      demoNotice: 'Modo demonstração: o número de WhatsApp ainda não foi configurado, então nenhuma conversa será aberta.',
      demoPreview: 'Esta seria a mensagem enviada:',
      opened: 'O WhatsApp foi aberto em uma nova aba com a sua mensagem.',
    },
    footer: {
      title: 'Vamos tirar seu projeto do papel?',
      text: 'Me conte sua ideia e vamos conversar sobre como posso ajudar.',
      cta: 'Entrar em contato',
      rights: 'Todos os direitos reservados.',
      linksLabel: 'Links',
    },
    notFound: {
      title: 'Esta página não existe',
      text: 'O endereço pode ter mudado. Os projetos continuam aqui:',
      cta: 'Ver projetos',
    },
  },

  en: {
    lang: 'en',
    ui: {
      skip: 'Skip to content',
      nav: { projects: 'Projects', about: 'About', contact: 'Contact' },
      navLabel: 'Main navigation',
      langLabel: 'Language',
      menuOpen: 'Open menu',
      menuClose: 'Close menu',
      home: 'Home',
      viewProject: 'View project',
      unavailable: 'Unavailable',
      linkPending: 'Link to be confirmed',
      placeholder: 'Placeholder image',
      conceptBadge: 'Concept project — fictional persona',
      pending: 'Pending',
      back: 'Back',
      projectNav: 'Browse projects',
      prevProject: 'Previous project',
      nextProject: 'Next project',
    },
    meta: {
      home: { title: 'João Riedo — Product Designer', description: 'Portfolio of João Riedo, Product Designer. Designing digital products, from structure to experience.' },
      projects: { title: 'Projects — João Riedo', description: 'Projects by João Riedo: Multi-tenant Design System, Instituto MAIS, Dr. Carlos Mattos and Marina Alves.' },
      about: { title: 'About — João Riedo', description: 'Experience, skills, education and certifications of João Riedo, Product Designer focused on UX/UI and Design Systems.' },
      contact: { title: 'Contact — João Riedo', description: 'Tell me about your project. Send João Riedo a message on WhatsApp.' },
      notFound: { title: 'Page not found — João Riedo', description: 'The page you are looking for does not exist.' },
    },
    home: {
      name: 'João Riedo',
      role: 'Product Designer',
      headline: 'Designing digital products, from structure to experience.',
      bio: 'I turned ambiguity into interfaces that actually work!',
      cta: 'Explore projects',
      skillsLabel: 'Skills',
      selectedTitle: 'Selected projects',
      scrollHint: 'Scroll to advance',
      testimonialsTitle: 'People I’ve worked with',
      testimonialsNav: 'Browse testimonials',
      prevTestimonial: 'Previous testimonial',
      nextTestimonial: 'Next testimonial',
    },
    projects: {
      title: 'Projects',
      intro: 'A design system, websites and landing pages I created, each with its challenge, solution and result.',
    },
    project: {
      breadcrumb: 'Projects',
      facts: { role: 'Role', duration: 'Duration', platform: 'Platform', team: 'Team' },
      live: 'Open live site',
      liveUnavailable: 'Site not yet published on this domain',
      mediaKit: 'Download media kit (PDF)',
      mediaKitUnavailable: 'Media kit (PDF) coming soon',
      demoTitle: 'Demo',
      desktop: 'Desktop',
      mobile: 'Mobile',
      fullscreen: 'Full screen',
      exitFullscreen: 'Exit full screen',
      demoPlaceholder: 'Placeholder demo',
      demoPlaceholderText: 'The navigable site will be embedded here. Meanwhile, this is a local preview.',
      demoLoading: 'Loading the site…',
      demoUnavailable: 'The site can’t be displayed here.',
      demoFallback: 'See the preview below or open the site in a new tab.',
      challengeTitle: 'Challenge',
      solutionTitle: 'Solution',
      resultTitle: 'Result',
      numbersNote: 'The numbers below describe the project’s scope, not business results.',
      next: 'Next project',
    },
    about: {
      title: 'I built systems that helped teams and products scale',
      intro: 'I built my career across graphic design, team leadership and B2B/B2C digital products. I worked as a Product Designer at Multibet and, before that, as a UX Designer for Cassino.bet and 7K.bet (Ana Gaming).',
      focusTitle: 'Design Systems, Design Ops and applied AI',
      focusText: 'I combined behavior analysis, information architecture and interface design with documentation and close collaboration with Engineering. I’ve built systems shared across brands and led redesigns with business results.',
      philosophyTitle: 'How I work',
      philosophy: [
        'I treated design as more than aesthetics: every visual decision I made answered a problem for the people who use the product and the people who build it.',
        'Design Ops with AI: I used Claude, ChatGPT, Figma Agent and Figma MCP and Notion MCP workflows to speed up ideation, prototyping, documentation and repetitive tasks, leaving more time for decisions that need judgment.',
        'I treated handoff as part of design: I delivered clear specs, documented components and design decision records (DDRs) so intent didn’t get lost in implementation.',
      ],
      differentialsTitle: 'Strengths',
      differentials: [
        { title: 'Multi-tenant Design Systems', text: 'I structured a Design System with 87 screens, 200+ components and 3 tenants in production, with an estimated 80% reduction in screen creation time.' },
        { title: 'Redesigns with results', text: 'I led the Cassino.bet sportsbook redesign; one month after launch, sports bets went from 3% to 10% of total betting volume.' },
        { title: 'End-to-end product', text: 'I ran projects from discovery and information architecture to interface, and built web pages with HTML, CSS and JavaScript.' },
        { title: 'Leadership and process', text: 'Led a team of 4, implemented Kanban and facilitated the Product team’s retrospectives.' },
      ],
      timelineTitle: 'Experience',
      timeline: [
        { org: 'Multibet', role: 'Product Designer', period: 'Feb–Sep 2026', note: 'I led product design for a B2B multi-tenant platform and structured the Design System for Supernova’s white-label operation, also applied to Play4tune and Multibet.' },
        { org: 'Cassino.bet and 7K.bet (Ana Gaming)', role: 'UX Designer', period: 'Apr–Dec 2025', note: 'I led the Cassino.bet sportsbook redesign, structured the information architecture for both brands and laid the groundwork for a shared Design System.' },
        { org: 'Alterra Mountain Company', role: 'Work and Travel', period: 'Dec 2023–Mar 2024', note: 'I took part in the winter season in Snowshoe, USA, and improved my English in a multicultural workplace.' },
        { org: 'Instituto ESPE', role: 'Design Supervisor', period: 'Sep 2020–Jul 2023', note: 'I supervised graphic and digital design production and led a team of 4.' },
      ],
      educationTitle: 'Education and skills',
      education: [
        { org: 'UniFil — Centro Universitário Filadélfia', course: 'Bachelor’s in Graphic Design', period: '2020–2022' },
        { org: 'IFPR, Londrina', course: 'Integrated IT Technician', period: '2015–2018' },
      ],
      skillsTitle: 'Skills',
      skills: ['UI & Prototyping', 'Design Systems', 'UX & Research', 'Applied AI', 'Web Development', 'Methods & Processes', 'Leadership & Soft Skills'],
      languagesTitle: 'Languages',
      languages: 'Portuguese (native) · English (advanced)',
      certificationsTitle: 'Certifications',
      certifications: [
        { name: 'Google UX Design Professional Certificate', issuer: 'Google / Coursera · 2026', url: 'https://www.coursera.org/account/accomplishments/specialization/Y2WKA6Q7A19U' },
        { name: 'Claude for Designers', issuer: 'Tera · 2026', url: 'https://credentials.somostera.com/d2a2aaf94c6cd04c9afdf55dcdadbebb' },
        { name: 'CCUSA Work Experience', issuer: 'CCUSA · Winter season 2023/2024', url: null, noLink: true },
      ],
      verify: 'View certificate',
      contactTitle: 'Direct contact',
      contactText: 'For proposals and project conversations, the contact page is the fastest way.',
      contactCta: 'Go to contact',
      cvTitle: 'Résumé',
      cvPt: 'Download résumé in Portuguese',
      cvEn: 'Download résumé in English',
      cvUnavailable: 'File not available yet',
      photoAlt: 'Photo of João Riedo',
    },
    contact: {
      title: 'Tell me about your project',
      text: 'Tell me your idea and let’s talk about how I can help.',
      otherChannels: 'Other channels',
    },
    form: {
      title: 'Shall we talk about your project?',
      text: 'Your message opens in WhatsApp, ready to send. Nothing is sent automatically.',
      name: 'Name',
      message: 'Message',
      submit: 'Send on WhatsApp',
      nameError: 'Please enter your name.',
      messageError: 'Please write a message.',
      greeting: (name) => `Hi João! This is ${name}.`,
      demoNotice: 'Demo mode: the WhatsApp number hasn’t been set up yet, so no conversation will be opened.',
      demoPreview: 'This is the message that would be sent:',
      opened: 'WhatsApp opened in a new tab with your message.',
    },
    footer: {
      title: 'Ready to get your project off the ground?',
      text: 'Tell me your idea and let’s talk about how I can help.',
      cta: 'Get in touch',
      rights: 'All rights reserved.',
      linksLabel: 'Links',
    },
    notFound: {
      title: 'This page doesn’t exist',
      text: 'The address may have changed. The projects are still here:',
      cta: 'See projects',
    },
  },
};
